### ISSUE TITLE
Support gpt-4o as a model option

### ISSUE THREAD

**Issue by tylerslaton** [gptscript-ai/gpt4-v-vision#18]
With `gpt-4o` now available we should make it available to use. Talking with the team, we'd likely want this to be the only option when we do add support for this.

Implementing this should be as simple as changing this line.
https://github.com/gptscript-ai/gpt4-v-vision/blob/6eacfe98695e4479bbff956dc24d066c18c9b2c0/index.js#L30-L33

**Comment by njhale** [comment]
Addressed by #20
